[build]
  command = "npm run build" # Adjust this to your build command
  publish = "dist" # Adjust to your build directory (could be "public", "dist", or others depending on your setup)

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
